"""Update models for instru_ownership and rental changes

Revision ID: 5a079737e1b3
Revises: e89e822ac2c2
Create Date: 2026-01-06 22:53:16.395092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a079737e1b3'
down_revision = 'e89e822ac2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_column('daily_rate')
        batch_op.drop_column('image_url')
        batch_op.drop_column('location')
        batch_op.drop_column('condition')
        batch_op.drop_column('is_available')

    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instru_ownership_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('rentals_instrument_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'instruments ownership', ['instru_ownership_id'], ['id'])
        batch_op.drop_column('instrument_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rentals_instrument_id_fkey'), 'instruments', ['instrument_id'], ['id'])
        batch_op.drop_column('instru_ownership_id')

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daily_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    op.drop_table('instruments ownership')
    # ### end Alembic commands ###
