"""Add user_type to User model

Revision ID: e89e822ac2c2
Revises: 
Create Date: 2026-01-05 16:30:39.738346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89e822ac2c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE users SET user_type = 'renter' WHERE user_type IS NULL")
    
    # Make it NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
